### ISSUE TITLE
Make a software paper 

### ISSUE THREAD

**Issue by saramahar** [mattbellis/hmis#10]
**Authors:** Does the paper.md file include a list of authors with their affiliations?
 **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
 **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by alexhanna** [comment]
This looks done.

**Comment by mattbellis** [comment]
Good point! Yikes! Lingering issues.
