### ISSUE TITLE
test data pickled files do not load in Python 2.7

### ISSUE THREAD

**Issue by alexhanna** [mattbellis/hmis#16]
The test data files do not unpickle when they are loaded in the Jupyter notebooks. They throw the following error:

<code>
ValueError: unsupported pickle protocol: 4
</code>

I'm guessing you will need to do a check for Python version and use a different pickled file for Python 2.7.

**Comment by mattbellis** [comment]
Ooohh....good catch. Will take care of this shortly.

**Comment by mattbellis** [comment]
OK, here's what I did.

Generated a new pickle file for testing and put it in test_data with a "_py27" added to the file name. 

Changed the README and readthedocs documentation to reflect that python 2.7 users should use this file when testing their installation. 

Changed the read function so that it throws an exception with a ValueError and has some more verbose output, suggesting that the user might want to check the version of python used to create the pickle file they are reading. 

This should all be pushed.

**Comment by alexhanna** [comment]
> Generated a new pickle file for testing and put it in test_data with a "_py27" added to the file name.

Okay, good.

> Changed the README and readthedocs documentation to reflect that python 2.7 users should use this file when testing their installation.

- You should still change http://hmis.readthedocs.io/en/latest/quickstart.html#requirements to reflect that 2.7 works with this package.
- Another change is that the first line of the README.md load for 2.7 has a comment character in front of it. Remove that.
`#people = hmis.read_dictionary_file('test_data/hmis_test_data_py27.pkl')`

> Changed the read function so that it throws an exception with a ValueError and has some more verbose output, suggesting that the user might want to check the version of python used to create the pickle file they are reading.

When I run this, the parser ends up passing the error back up to another function, resulting in a NoneType error. Better to write your change such that it throws the ValueError, like so:

```
    try:
        dictionary_list = pickle.load(infile)
    except ValueError as detail:
        error_string = """%s
This is most likely caused by the file being pickled with a higher protocol in Python3.x and then trying to open it with a lower protocol in 2.7.
You will want to recreate the file using the same version of python as the one you are using to open it
File is not read in!""" % detail
        raise ValueError(error_string)

```

**Comment by mattbellis** [comment]
Ah, nice. OK, I added that. 

I also found that when a pickle file is created with 2.7 and read in with 3.x, one gets a UnicodeDecodeError. I added a catch for that as well. Tested both and it seems to work. 



```
    infile = open(filename, 'rb')
    try:
        dictionary_list = pickle.load(infile)
    except ValueError as detail:
        error_string = """%s
        This is most likely caused by the file being pickled with a higher protocol in Python3.x and then trying to open it with a lower protocol in 2.7.\n
        You will want to recreate the file using the same version of python as the one you are using to open it.\n
        File is not read in!""" % detail
        raise ValueError(error_string)
    except UnicodeDecodeError as detail:
        error_string = """%s
        This is most likely caused by the file being pickled with a lower protocol in Python2.7 and then trying to open it with a higher protocol in 3.x.\n
        You will want to recreate the file using the same version of python as the one you are using to open it.\n
        File is not read in!""" % detail

```

**Comment by alexhanna** [comment]
Looks good. 

I created a [quick pull request](https://github.com/mattbellis/hmis/pull/20) for the README.md error. Once you merge it, I'll close this issue and approve the JOSS review.

**Comment by mattbellis** [comment]
Done! Thank you for all your super helpful and super timely feedback!
