### ISSUE TITLE
selection_and_visualizing_program_mapping.ipynb doesn't show any locations

### ISSUE THREAD

**Issue by alexhanna** [mattbellis/hmis#17]
I tried running plot_program_locations in selection_and_visualizing_program_mapping.ipynb and it did not show any locations, clustering or not.

**Comment by mattbellis** [comment]
Fixed. Mock data provided by community partners had a dummy zip code (99999) for CoC locations. Changed it to be 12210, the zip code for Albany, NY, and regenerated the .pkl file from those .csv files. 

Verified that the notebook now produces the correct markers on the maps.

**Comment by alexhanna** [comment]
Looks the same. Have you committed the changes?

**Comment by mattbellis** [comment]
Oops! So sorry. Just did it.

**Comment by alexhanna** [comment]
No worries. Looks good.
