### ISSUE TITLE
needs release per JOSS guidelines

### ISSUE THREAD

**Issue by alexhanna** [mattbellis/hmis#19]

**Comment by mattbellis** [comment]
Added __version__ to hmis/hmis/__init__.py

Release is already defined in docs/conf.py. Is there somewhere else I'm missing it? I couldn't find anywhere else on JOSS's site that might mention somewhere else I'm missing it. Sorry if I'm missing something obvious.

**Comment by alexhanna** [comment]
Sorry, should have been more clear. JOSS checklist says the following:

Version: Does the release version given match the GitHub release (1.0)?

So I'm assuming you need to create a Github release: https://github.com/mattbellis/hmis/releases

**Comment by mattbellis** [comment]
Ah, of course. Got it. Done.
